### ISSUE TITLE
"openiduser"s

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1187] opened 2015-12-14 17:38 UTC
Who: Luca

There are many accounts on the system with username "openiduserN" where N is an integer. All these accounts originate from people that log in with an openid from CEDA, which has turned off attribute exchange. For example:

user id = 883
openid = https://ceda.ac.uk/openid/YuenTungEunice.Lo
CoG page: https://www.earthsystemcog.org/user/detail/883/

Can we change their username to be something different instead of "openiduserN" ?

**Comment by LucaCinquini** [comment] 2015-12-14 17:39
BTW the site administrator can change the username of existing users by using the django admin interface.

**Comment by murphysj** [comment] 2015-12-14 17:45
THis is a duplicate of #1025

**Comment by murphysj** [comment] 2015-12-14 17:45
The CU node as a bunch of these too.

**Comment by LucaCinquini** [comment] 2015-12-14 17:47
Yes that is the node I am worried about. I am going to try to find a solution for new accounts, then we can probably go and change the username of the existing ones.

**Comment by murphysj** [comment] 2015-12-14 17:49
sounds good. 

I am going to close this ticket as a duplicate. Use #1025 to record your efforts. I put it into 3.1.2

**Closed by murphysj** 2015-12-14 17:49 UTC
Labels: Bugs
