### ISSUE TITLE
Redirecting to original page after new account creation

### ISSUE THREAD

**Issue by LucaCinquini** [EarthSystemCoG/COG#1016] opened 2015-03-10 16:15 UTC
Who: Cecelia

Dealing with someone confused by new account creation sending you to the NOAA CoG
site.... It would be much better to redirect back to the page they were on when
they did the Create Account request.

**Comment by LucaCinquini** [comment] 2015-03-10 16:17
Duplicate of 1017

**Comment by murphysj** [comment] 2015-04-09 15:05
duplicate of 1032. This was done in 2.11.

**Closed by murphysj** 2015-04-09 15:05 UTC
Labels: Feature requests, system
